#!/usr/bin/env bash
# Generates the throwaway TLS and credential material for the strict-security profile.
#
# A local development CA and one broker certificate, in PEM. PEM rather than JKS because Kafka has
# supported it since 2.7 and it needs no keystore passwords, which are security theatre for
# certificates that live in a gitignored directory and are regenerated on demand.
#
# It also writes the SASL passwords to deploy/compose/.env and per-identity client properties. Those
# do not go in the compose file because the compose file is committed, and NFR-05.10 rules out
# credential material in source regardless of how worthless the credential is. The passwords match
# SecureKafkaStack's scheme, so the same identity means the same thing in the stack and in the tests.
#
# None of this is committed. Regenerate at any time; the stack picks it up on the next start.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CERT_DIR="$REPO_ROOT/deploy/compose/tls"
DAYS=825

log() { printf '\033[1m==>\033[0m %s\n' "$*"; }

command -v openssl >/dev/null || { echo "openssl is required" >&2; exit 1; }

mkdir -p "$CERT_DIR"
cd "$CERT_DIR"

log "generating the development certificate authority"
openssl req -x509 -newkey rsa:2048 -nodes \
  -keyout ca.key -out ca.pem -days "$DAYS" \
  -subj "/CN=fes-local-dev-ca/O=financial-event-streaming-platform/OU=local-only" 2>/dev/null

# One certificate covers all three brokers. Hostname verification is left on, so every name a client
# might use has to be in the SAN list: the container names for in-network clients and localhost for
# anything connecting through the published ports.
log "generating the broker certificate"
cat > broker.cnf <<'CNF'
[req]
distinguished_name = dn
req_extensions = ext
prompt = no

[dn]
CN = kafka
O = financial-event-streaming-platform
OU = local-only

[ext]
subjectAltName = DNS:kafka1,DNS:kafka2,DNS:kafka3,DNS:localhost,IP:127.0.0.1
extendedKeyUsage = serverAuth
CNF

openssl req -newkey rsa:2048 -nodes -keyout broker.key -out broker.csr -config broker.cnf 2>/dev/null
openssl x509 -req -in broker.csr -CA ca.pem -CAkey ca.key -CAcreateserial \
  -out broker.crt -days "$DAYS" -extfile broker.cnf -extensions ext 2>/dev/null

# Kafka's PEM keystore is one file holding the certificate chain and the private key.
cat broker.crt ca.pem broker.key > broker.keystore.pem

chmod 644 ca.pem broker.keystore.pem
rm -f broker.csr broker.cnf ca.srl

log "wrote deploy/compose/tls: ca.pem (truststore), broker.keystore.pem (broker identity)"

# Identities the broker accepts. Must match SecureKafkaStack.PRINCIPALS, or a service proven to be
# least-privilege in a test would authenticate as something else in the stack.
PRINCIPALS=(admin trade-producer market-data-simulator corporate-action-producer reference-data-service audit-service)

secret_for() { printf '%s-local-secret' "$1"; }

log "writing SASL credentials"
{
  echo "# Generated by scripts/generate-dev-security-material.sh. Never committed."
  echo "# Local development credentials for the strict-security profile. Not secrets."
  for principal in "${PRINCIPALS[@]}"; do
    printf 'FES_PASSWORD_%s=%s\n' "$(echo "$principal" | tr 'a-z-' 'A-Z_')" "$(secret_for "$principal")"
  done

  # The broker's JAAS entry, assembled here so the committed compose file carries no password.
  jaas='org.apache.kafka.common.security.plain.PlainLoginModule required'
  jaas="$jaas username=\"admin\" password=\"$(secret_for admin)\""
  for principal in "${PRINCIPALS[@]}"; do
    jaas="$jaas user_${principal}=\"$(secret_for "$principal")\""
  done
  printf 'FES_BROKER_JAAS=%s;\n' "$jaas"

  printf 'FES_ADMIN_JAAS=%s username="admin" password="%s";\n' \
    'org.apache.kafka.common.security.plain.PlainLoginModule required' "$(secret_for admin)"
} > "$REPO_ROOT/deploy/compose/.env"
chmod 600 "$REPO_ROOT/deploy/compose/.env"

# Client properties per identity, so a developer can point kafka-console-producer at the stack as a
# specific workload and watch least privilege apply to them.
for principal in "${PRINCIPALS[@]}"; do
  cat > "$CERT_DIR/client-$principal.properties" <<PROPS
security.protocol=SASL_SSL
sasl.mechanism=PLAIN
sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="$principal" password="$(secret_for "$principal")";
ssl.truststore.type=PEM
ssl.truststore.location=/etc/kafka/secrets/ca.pem
PROPS
done
chmod 600 "$CERT_DIR"/client-*.properties

log "wrote deploy/compose/.env and per-identity client properties"
log "valid for $DAYS days, for local development only"
